version: '3.8'
services:
  reservations:
    image: reservation
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: dev
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sleepr
    depends_on:
      - mongodb
  payments:
    image: payment
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: dev
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sleepr
    depends_on:
      - mongodb
  auth:
    image: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: dev
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sleepr
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'